name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v2

    - name: Configure
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build
